print("Name: K THEJAS SUVARNA")
print("Admission no.: 0407/CS/2025-26")
print("Semester: 1")
print("Section: B")
print("COMPUTER SCIENCE AND ENGINEERING")
print("SUBJECTS  AND SCORES:")
print("Introdution to Mechanical Engineering: (3-CREDIT)")
print("CIE 1: 21/45")
print("CIE-2: 29/45")
print("Average in CIE: 9/15")
print("Practical Record: 8/10")
print("Assignment: 8/10")
print("Lab Examination: 12/15")
print("Total: 37/50")