print("Hello, Everyone.")
print("My name is K THEJAS SUVARNA.")
print("I am 19 years old.")
print("Date of Birth: 07-10-2006")
print("My Blood Group is B+")
print("I am studying at Sahyadri College of Engineering and Management")
print("My father name is Ganesh Poojari")
print("My mother name is K Saraswathi")
print("I am presently studing in 1 Semester CSE Branch B Section.")
print("My roll no. is 37 and my admission no. is 0407/CS/2025-26")